<?php session_start();
global $mk_options;
global $wpdb;
?>

<h5 class="recent_bookings">Your Recent Bookings</h5>
<p class="this_section_pro">
  <!--This section provides information on your itinerary, trip details and booked tickets. ... used to make the booking and the system will show your recent bookings.	 -->
  This section provides information on your offers and enquiry generated by PetsonBreak website.... the system will show your recent enquiry generated.
  </p>
<div class="table_background  booking-table-container" style="width:100%;">
<table class="booking_table" width="100%" cellspacing="0" cellpadding="0" border="0">
<tbody><tr class="book-table-headings">
<td>Booking Id</td>
<td>Hotel Name</td>	
<td>Name</td>
<td>Email</td>			
<td>Checkin</td>
<td>Checkout</td>
<td>Status</td>
<td>Price</td>
<td>&nbsp;</td>
</tr>

<?php 
$results =$wpdb->get_results("select * from twc_booking where login_id='".$_SESSION['userID']."'");
if(count($results)){
 foreach($results as $obj){ ?>
  <tr>
	<td>
	<a href="javascript:void(0)" onclick="window.open('<?php echo site_url();?>/#/confirmation/<?php echo $obj->itineraryId; ?>', '_blank', 'location=yes,height=570,width=1200,scrollbars=yes,status=yes')"><?php echo $obj->itineraryId; ?></a>
	</td>
	<td><?php echo $obj->hotelName; ?></td>
	<td><?php echo $obj->user_name; ?></td>
	<td><?php echo $obj->user_email; ?></td>
	<td><?php echo $obj->check_in; ?></td>
	<td><?php echo $obj->check_out; ?></td>
	<td><?php echo $obj->booking_status; ?></td>
	<td><?php echo $obj->currency_code.' '.$obj->chargable_rate; ?></td>
	<?php if($obj->booking_status=='Cancelled'){?>
	<td>Cancellation No. <?php echo $obj->cancellationNumber;?> </td>
	<?php } else{?>
	<td><a href="javascript:void(0);" onclick="BookingCancel('<?php echo $obj->itineraryId; ?>','<?php echo $obj->confirmationNumbers; ?>','<?php echo $obj->user_email; ?>')" >Cancel Booking</a></td>
	<?php } ?>
  </tr>
<?php }} else{ ?>
<tr>
	<td colspan="3">No Data</td>
</tr>	
<?php }?>
</tbody></table>
</div>

 

 
<style>
#mng-services #postform .modalFields li label {
    float: left;
    width: 100%;
}

.payment-options{
	width: 100%;
	float: left;
	margin-bottom: 25px;
}



.modalFields li label {
    display: block;
    font-size: 16px;
    color: #777;
    font-weight: 300;
    font-style: italic;
    margin-bottom: 7px;
}
.modalFields li {
    float: left;
    width: 100%;
}
.modalFields li input, select,textarea {
    height: 40px;
    margin-bottom: 25px;
    width: 100%;
    padding: 5px 5px 5px 9px;
    border-radius: 4px;
    border: 1px solid #777;
}
#mng-services .modalFields li input,select, textarea {
    float: right;
    width: 100%;
}



 #postform{}
 #postform .modalLogin-loginFields li label{float: left;width: 20%;}
 #postform .modalLogin-loginFields li input{float: right;width: 78%;}
 .Description-inputoo{width: 100%;float: left;}
 .Description-inputoo textarea{position: relative;
    width:100%;
    height: auto;
}

#mng-services #postform .payment-options > label{
	display: inline;
    width: 67px !important;
    margin-right: 10px;
    padding-left: 0px;
    }

#mng-services #postform .payment-options > label>span{
    display: inline-block;
    float: left;
    width: 50%;
}

#mng-services #postform .payment-options > label>input{
	display: inline-block;
    width: auto;
    height: auto;
    width: 50%;
    margin-right: 0px;
    margin-bottom: 0px;
    margin-left: 0px ;
}

#mng-services #postform #image_path{
 	border: 0px;
    padding-left: 0px;
	height: auto;	
}
.add-serv-row{
	margin-top: 20px;
    display: table;
}

.add-serv-row .col-md-6{
    display: table-cell;
}

.add-serv-row .col-md-6:first-child{
	border-right: 1px solid #ccc;
}



.recent_bookings{
	font-size: 31px !important;
    color: #333 !important;
    font-weight: 500 !important;
}

.recent_bookings span{
    font-weight: 600;
    color: #636 !important;
    position: relative;
    bottom: 3px;
}

.recent_bookings span a{
    font-size: 20px;
    color: #636;
    text-decoration: underline;
}

.upload_div{
	width: 40%;
    float: left;
}

.upld_img_div{
	width: 50%;
    float: left;
    max-height: 200px;
    background: #f3f3f3;
    text-align: center;
}

.upld_img_div img{
	width: 100%;
    height: 100%;
}

 </style>